;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
				electric-newline-and-maybe-indent
				indent-for-tab-command
				indent-region
				isearch-abort
				org-self-insert-command
				))

(setq mc/cmds-to-run-once
      '(
				beginning-of-buffer
				comment-dwim
				electric-pair-delete-pair
				end-of-buffer
				find-file
				forward-sentence
				goto-line
				isearch-forward-symbol-at-point
				kill-region
				make-frame
				mark-whole-buffer
				mode-line-previous-buffer
				mouse-drag-mode-line
				mouse-minor-mode-menu
				mouse-select-window
				moz-send-region
				projectile-find-file
				switch-to-buffer
				))
